# TAG 3 – NumPy Basics (Verständnis > Syntax)

Ziel dieses Notebooks:

- verstehen, was NumPy ist
- erklären können, warum es wichtig ist
- Shapes sicher interpretieren
- Broadcasting sauber erklären
- vektorisierte Operationen anwenden

Kein unnötiger Theorieballast.
Fokus: Interview-Performance.


## Was ist NumPy?

Kurzfassung:
NumPy ist die Basisbibliothek für numerische Datenverarbeitung in Python.

Interview-tauglich:
NumPy stellt effiziente, mehrdimensionale Arrays bereit und bildet die Grundlage für viele Data-Science- und Machine-Learning-Bibliotheken.

Warum wichtig?
- Pandas baut darauf auf
- Scikit-learn nutzt NumPy Arrays
- TensorFlow verarbeitet NumPy-Strukturen


## Python Liste vs NumPy Array

Python Liste:
- flexibel
- gemischte Datentypen möglich
- langsam bei numerischen Operationen
- Schleifen nötig

NumPy Array:
- homogener Datentyp
- speichereffizient
- vektorisierte Berechnungen


In [102]:
import numpy as np

# Python Liste
revenues_list = [100, 200, 300]

# NumPy Array
revenues_array = np.array([100, 200, 300])

revenues_array


array([100, 200, 300])

## Was bedeutet vektorisiert?

Vektorisiert bedeutet:
Eine Operation wird auf ein ganzes Array gleichzeitig angewendet,
ohne explizite Python-Schleife.


In [103]:
#Nicht vektorisiert muss iteriert werden
result = []
for x in revenues_list:
    result.append(x * 1.1)

print(result)

#Vektorisiert kann auf alle Elemente gleichzeitig angewendet werden
scaled = revenues_array * 1.1

print(scaled)



[110.00000000000001, 220.00000000000003, 330.0]
[110. 220. 330.]


Interview-Satz:

NumPy erlaubt mir, numerische Operationen auf ganzen Datenblöcken
gleichzeitig auszuführen, ohne Python-Schleifen.


## Was ist shape?

Das Shape beschreibt:
- wie viele Dimensionen ein Array hat
- wie groß jede Dimension ist


## Eindimensional

In [104]:
a = np.array([1, 2, 3])
a.shape


(3,)

Interpretation:
3 Elemente, 1 Dimension.


## Zweidimensional

In [105]:
b = np.array([[1, 2], [3, 4]])
b.shape


(2, 2)

Interpretation:
2 Zeilen, 2 Spalten.




Das Shape bestimmt, wie Daten interpretiert und weiterverarbeitet werden.
Falsche Shapes führen häufig zu Modellfehlern.

## Broadcasting – einfach erklärt

Broadcasting bedeutet:
NumPy passt kleinere Arrays automatisch an größere an,
wenn die Operation mathematisch sinnvoll ist.


In [106]:
a = np.array([100, 200, 300])
a * 1.1


array([110., 220., 330.])

Broadcasting ermöglicht Operationen zwischen unterschiedlich
geformten Arrays ohne explizite Schleifen.


## Typische Data-Science-Operationen

Mittelwert und Standardabweichung

In [107]:
a = np.array([100, 200, 300])

mean = a.mean()
std = a.std()

print('Mean:', float(mean))
print('Standard Deviation:', float(std))




Mean: 200.0
Standard Deviation: 81.64965809277261


Normalisierung

In [108]:
normalized = (a - a.mean()) / a.std()
print(normalized)
normalized

[-1.22474487  0.          1.22474487]


array([-1.22474487,  0.        ,  1.22474487])

Use Case:
Feature Scaling vor ML-Modellen.

### Aufgabe:

1. Erstelle ein NumPy Array aus einer Liste von Umsätzen
2. Multipliziere alle Werte mit 1.2
3. Gib das Shape aus


In [ ]:
import numpy as np

revenues = [120, 300, 980]
arr = np.array(revenues)

scaled_arr = arr * 1.2

print("Skalierte Werte:", scaled_arr)
print("Shape:", scaled_arr.shape)


Skalierte Werte: [ 144.  360. 1176.]
Shape: (3,)


# Warum ist NumPy schneller als Python-Listen?


NumPy arbeitet mit homogenen Arrays und führt Operationen vektorisiert im optimierten C-Code aus.
##

# Was sagt das Shape eines Arrays aus?

Es beschreibt die Anzahl der Dimensionen und die Größe jeder Dimension.
##

# Was ist Broadcasting?

Ein Mechanismus, der Operationen zwischen unterschiedlich geformten Arrays automatisch ermöglicht.
